<a href="https://colab.research.google.com/github/farahnda/Learning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [21]:
df = pd.read_csv('social_network_ads.csv')

In [22]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [24]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [25]:
gender = pd.get_dummies(df['Gender'], drop_first=True)
df = pd.concat([df, gender], axis=1)

In [26]:
df.drop(['Gender'], axis=1, inplace=True)

In [27]:
X = df[['Age', 'EstimatedSalary', 'Male']]
y = df['Purchased']

In [28]:
from sklearn.preprocessing import StandardScaler # buat standarin data yg panjangnya beda
scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [29]:
StandardScaler()

StandardScaler()

In [31]:
scaled_features = scaler.transform(X)
scaled_features

array([[-1.78179743, -1.49004624,  1.02020406],
       [-0.25358736, -1.46068138,  1.02020406],
       [-1.11320552, -0.78528968, -0.98019606],
       ...,
       [ 1.17910958, -1.46068138, -0.98019606],
       [-0.15807423, -1.07893824,  1.02020406],
       [ 1.08359645, -0.99084367, -0.98019606]])

In [32]:
df_feat = pd.DataFrame(scaled_features, columns=X.columns)
df_feat.head()

        Age  EstimatedSalary      Male
0 -1.781797        -1.490046  1.020204
1 -0.253587        -1.460681  1.020204
2 -1.113206        -0.785290 -0.980196
3 -1.017692        -0.374182 -0.980196
4 -1.781797         0.183751  1.020204

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scaled_features, y, test_size=0.2)

In [36]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1) # ambil 1 tetangga dekatnya aja
knn.fit(X_train, y_train) # model prediksi

KNeighborsClassifier(n_neighbors=1)

In [37]:
KNeighborsClassifier(n_neighbors=1) # belajar

KNeighborsClassifier(n_neighbors=1)

In [38]:
pred = knn.predict(X_test)  # model test prediksi

In [39]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test, pred)

array([[46,  5],
       [ 2, 27]])

In [40]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.96      0.90      0.93        51
           1       0.84      0.93      0.89        29

    accuracy                           0.91        80
   macro avg       0.90      0.92      0.91        80
weighted avg       0.92      0.91      0.91        80